spring:
  datasource:
    pre :
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.32.189.250:3306/chexiangpai?useUnicode=true&amp;characterEncoding=utf8&amp;characterResultSets=utf8
      user: chexiangpai
      password: chexiangpai
    sit :
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.32.173.250:3306/chexiangpai?useUnicode=true&amp;characterEncoding=utf8&amp;characterResultSets=utf8
      user: chexiangpai
      password: chexiangpai

    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    # driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
mybatis:
  mapperLocations: classpath:/com/xiateng/mapper/*/*.xml
  typeAliasesPackage: com.xiateng.entity
  configuration:
    cache-enabled: true

# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
  level:
    root: info
    com.xiateng.dao.user: debug

object:
  name: Object
  blogurl: blog.objectspace.cn